global:
  edition: ce
  hosts:
    domain: gitlab.local
    https: false
    gitlab:
      name: gitlab.local
      https: false
    
  ingress:
    enabled: true
    configureCertmanager: false
    class: "traefik"
    annotations:
      kubernetes.io/ingress.class: "traefik"
    tls:
      enabled: false

  shell:
    port: 22

nginx-ingress:
  enabled: false

prometheus:
  install: false

gitlab-runner:
  install: false

registry:
  enabled: false

gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
    # resources:
    #   requests:
    #     cpu: 200m
    #     memory: 1.5G
    #   limits:
    #     memory: 2G
  
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 600M
    #   limits:
    #     memory: 1G
  
  gitaly:
    minReplicas: 1
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 200M
    #   limits:
    #     memory: 500M
  
  gitlab-shell:
    minReplicas: 1
    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 100M
    #   limits:
    #     memory: 200M

# postgresql:
#   resources:
#     requests:
#       cpu: 100m
#       memory: 256M
#     limits:
#       memory: 512M

# redis:
#   master:
#     resources:
#       requests:
#         cpu: 50m
#         memory: 100M
#       limits:
#         memory: 256M
