apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k3d-gitlab
  namespace: gitlab
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    spec.ingressClassName: "traefik"
spec:
  rules:
    - host: iot.local.gitlab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab-webservice-default
                port:
                  number: 8081